// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtjKaXdmnb1p9bvh_FUf7tabpdyDRNXhk',
    appId: '1:827691932766:web:859ab07e96c0e4781528cf',
    messagingSenderId: '827691932766',
    projectId: 'foodorderingapplication-b2799',
    authDomain: 'foodorderingapplication-b2799.firebaseapp.com',
    databaseURL: 'https://foodorderingapplication-b2799-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'foodorderingapplication-b2799.appspot.com',
    measurementId: 'G-58ZYYXVH31',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCN2tAhIxm6_PY4VeGdcZ8ELLrxcXBzFQc',
    appId: '1:827691932766:android:5bd9e8610e4d8d911528cf',
    messagingSenderId: '827691932766',
    projectId: 'foodorderingapplication-b2799',
    databaseURL: 'https://foodorderingapplication-b2799-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'foodorderingapplication-b2799.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpNxJVrFO3UVOggV0J49WLZWIGkyTossc',
    appId: '1:827691932766:ios:c637d893ce28f4f71528cf',
    messagingSenderId: '827691932766',
    projectId: 'foodorderingapplication-b2799',
    databaseURL: 'https://foodorderingapplication-b2799-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'foodorderingapplication-b2799.appspot.com',
    iosClientId: '827691932766-tq9j757tvq43rl1q2b5pj9pf2ttdd29b.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodOrderingApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpNxJVrFO3UVOggV0J49WLZWIGkyTossc',
    appId: '1:827691932766:ios:c637d893ce28f4f71528cf',
    messagingSenderId: '827691932766',
    projectId: 'foodorderingapplication-b2799',
    databaseURL: 'https://foodorderingapplication-b2799-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'foodorderingapplication-b2799.appspot.com',
    iosClientId: '827691932766-tq9j757tvq43rl1q2b5pj9pf2ttdd29b.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodOrderingApplication',
  );
}
